### ISSUE TITLE
Spaces before inline math is removed

### ISSUE THREAD

**Issue by ppwwyyxx** [next-theme/hexo-filter-mathjax#42]
My markdown looks like this:
```
flipped by  $i \leftarrow W - 1 - i$
```

Before, I was using frontend rendering with mathjax javascript library. The space between "by" and the inline math is kept. I got result like this:
![2022-02-27_22-49](https://user-images.githubusercontent.com/1381301/155937310-006f60cf-a3d9-4e06-8aac-6ec5facc8c02.png)

After using `hexo-filter-mathjax`, the space disappeared and I got this:
![2022-02-27_22-50](https://user-images.githubusercontent.com/1381301/155937379-5d67af93-a3e8-4869-9073-0b9386801e39.png)

I can also see from the raw html that the space is gone.

Is this a problem of `hexo-filter-mathjax`? How can I let it render the space properly?

Options that I use:
```
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  extension_options: {}
```
