### ISSUE TITLE
矩阵公式未渲染

### ISSUE THREAD

**Issue by Tiramisu-MH** [next-theme/hexo-filter-mathjax#58]
- use theme: Keep v3.6.1
- Hexo v6.3.0
- Hexo config.yml
```
 mathjax:
  tags: none               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article
```
- article Front-matter
```
title: 为什么学习矩阵
date: 2022-09-14 22:23:55
tags: [数学, 矩阵]
categories: 思考
mathjax: true
```
- problem: 矩阵公式乱码
- 本地渲染图片
![image](https://user-images.githubusercontent.com/57339938/215240324-50ce969b-790d-41b8-aa32-72c94c4c7e2d.png)
- Typora 渲染图片
![image](https://user-images.githubusercontent.com/57339938/215240372-7818e661-6a44-4e56-a016-a159f04bb0a9.png)
