### ISSUE TITLE
数学公式不显示编号

### ISSUE THREAD

**Issue by formath** [next-theme/hexo-filter-mathjax#59]
渲染插件：
hexo-filter-mathjax
hexo-renderer-pandoc

mathjax配置：
```
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: true # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages: # extra packages to load
  extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail
```

文章中公式latex例子：
```
$$
\begin{equation}
\begin{aligned}
p(x) = \frac{exp^{u(x;\,\theta)}}{Z(\theta)}
\end{aligned}
\end{equation}
$$
```
